services:
  # backend-ferremas:
  #   build:
  #     context: ./backend
  #   image: backend-ferremas
  #   ports: 
  #     - "8080:8080"
  #   container_name: backend-ferremas
  #   depends_on:
  #     - db-mysql  
  #   networks:
  #     - network_custom

  db-mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: ferremas    
        MYSQL_USER: user       
        MYSQL_PASSWORD: pass 
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
